[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cookie = "0.18.1"
reqwest = { version = "0.12.3", features = ["json"] }
tokio = { version = "1", features = ["full"] }

